apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: myimage
  newName: 600086062597.dkr.ecr.ap-northeast-2.amazonaws.com/erik-test
  newTag: 7cafabddfae9c831a145b4a0cc5ed415f33c40ca
